// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbKYzjzSsOs3N47f3EESH-tB264mZuIOo',
    appId: '1:578373083632:android:b3a27e69f3449eb146bd35',
    messagingSenderId: '578373083632',
    projectId: 'hackattack---neutrago',
    authDomain: 'hackattack---neutrago.firebaseapp.com',
    // storageBucket: 'hackattack---neutrago.appspot.com',
    storageBucket: 'hackattack---neutrago.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbKYzjzSsOs3N47f3EESH-tB264mZuIOo',
    appId: '1:578373083632:android:b3a27e69f3449eb146bd35',
    messagingSenderId: '578373083632',
    projectId: 'hackattack---neutrago',
    storageBucket: 'hackattack---neutrago.firebasestorage.app',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'YOUR-IOS-API-KEY',
  //   appId: 'YOUR-IOS-APP-ID',
  //   messagingSenderId: 'YOUR-SENDER-ID',
  //   projectId: 'YOUR-PROJECT-ID',
  //   storageBucket: 'YOUR-PROJECT-ID.appspot.com',
  //   iosBundleId: 'com.example.hackattack',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'YOUR-MACOS-API-KEY',
  //   appId: 'YOUR-MACOS-APP-ID',
  //   messagingSenderId: 'YOUR-SENDER-ID',
  //   projectId: 'YOUR-PROJECT-ID',
  //   storageBucket: 'YOUR-PROJECT-ID.appspot.com',
  //   iosBundleId: 'com.example.hackattack',
  // );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'YOUR-WINDOWS-API-KEY',
  //   appId: 'YOUR-WINDOWS-APP-ID',
  //   messagingSenderId: 'YOUR-SENDER-ID',
  //   projectId: 'YOUR-PROJECT-ID',
  //   storageBucket: 'YOUR-PROJECT-ID.appspot.com',
  // );
}
